### ISSUE TITLE
Compile  error on Mac OSX 10.2 (Sierra)

### ISSUE THREAD

**Issue by bemoregt** [bakercp/ofxDlib#11]
Hi, @bakercp 

Compile Error on Mac OSX 10.2 (Sierra)
like this 
--------------------------------
In file included from /Users/dti/Documents/of_v0.9.8_osx_release/addons/ofxDlib/src/ofxDlib.h:12:
/Users/dti/Documents/of_v0.9.8_osx_release/addons/ofxDlib/libs/ofxDlib/include/ofx/Dlib/Utils.h:12:10: fatal error: 
      'dlib/geometry.h' file not found
#include <dlib/geometry.h>
         ^
1 error generated.
make[1]: *** [obj/osx/Release/src/main.o] Error 1
make: *** [Release] Error 2
kraken:example_dnn_face_recognition dti$ 
---------------------------------------------------
What's wrong ?

**Comment by bakercp** [comment]
Please check the README regarding supported versions of oF.

**Comment by CedarZhou** [comment]
get same error, and check README as suggested, still have no idea where to find solution

**Comment by bakercp** [comment]
0.9.8 is not supported.  You must use the master branch.
