### ISSUE TITLE
deprecating my addon (ofxDLib)

### ISSUE THREAD

**Issue by roymacdonald** [bakercp/ofxDlib#5]
Hi Chris!
I'm going to deprecate my addon. I think that the only valuable thing in there are the examples. Do you think that it is worth adding these examples to your addon? These are:

- FaceTracker
- HOGLabeler
- HOGTrainer
- ObjectTracker

If you think so please let me know and I'll adapt these to use your addon and make a PR.

Take care.

cheers!

**Comment by bakercp** [comment]
I'd definitely be interested in merging these examples. I want to minimize "wrapping", but as we've seen from ofxCv, a few helper classes for common tasks (like FaceTracker, ObjectTracker, etc) can be really useful.  So, go for it!  CB

**Comment by roymacdonald** [comment]
great! I will PR during the weekend.
best
