### ISSUE TITLE
install / build scripts failing

### ISSUE THREAD

**Issue by vvzen** [bakercp/ofxDlib#7]
I tried building with make on **OS X El Capitan 10.11.2**.

I ran the _build.sh_ , but it had some issues in using _ostype.sh_ (it asked me for permissions even after chmodding it 777 and using _sudo_ , so I ended up inserting _osx_ manually in the build.sh file).

Here's a screen after my build.sh:

![screen shot 2017-05-13 at 12 32 06](https://cloud.githubusercontent.com/assets/10340139/26024742/8f7e446e-37d8-11e7-8d99-88e619fac26f.png)

For some reasons also the script wasn't able to pickup my env var $OF_ROOT, so I had to insert it manually in the script.
Also I don't know if the install.sh in line 66 should actually be the _install.sh_ of this addon.
I'm quite new to all of this build thing so forgive me for any error!

Thanks! 😁

**Comment by bakercp** [comment]
Try the scripts again -- I was working on them for CI and they were in a bad state.

**Comment by AnasGhrab** [comment]
There are still problems. I had to change ```build.sh``` to ```./build.sh``` inside install.sh but I still get : 

```
MACHINE CONFIG
==============
           TARGET:

ADDON CONFIG
============
        ADDON_NAME: scripts
        ADDON_PATH: /Users/anas/of_v0.9.8_osx_release/addons/scripts
ADDON_SCRIPTS_PATH: /Users/anas/of_v0.9.8_osx_release/addons/scripts/scripts

Apothecary not installed, installing latest version.
fatal: destination path '/Users/anas/of_v0.9.8_osx_release/scripts/apothecary' already exists and is not an empty directory.
No additional apothecary dependencies to install.
Done installing apothecary.
Building ofxDlib libraries for osx ...
./build.sh: line 68: /Users/anas/of_v0.9.8_osx_release/scripts/apothecary/apothecary/apothecary: Not a directory
```
I don't know what is ```Apothecary```.

**Comment by bakercp** [comment]
Please have a look at the README. This again is not compatible with the stable openFrameworks branch. It appears you are using 0.9.8.

**Comment by saynono** [comment]
I had the same issue with the install script.
I changed the apothecary/install.sh script to this:
LINE 20:
  ADDON_NAME="$(basename $( cd "$( dirname "${BASH_SOURCE[0]}" )/../../" && pwd ))"

This changes the ADDON_NAME from "script" to "ofxDlib"
Also the download_models_and_data.sh script is only in the develop-branch.
Edit:
Using osx 10.12, of-master and ofxDlib-master

**Comment by bakercp** [comment]
This is fixed on the develop branch.  Call `scripts/./bootstrap.sh`.
