### ISSUE TITLE
cblas problem?

### ISSUE THREAD

**Issue by vrx** [bakercp/ofxDlib#8]
On Ubuntu 16.04 64 bits :

When running build.sh i get
-- C++11 activated.
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Found OpenBLAS library
-- Looking for sgetrf_single
-- Looking for sgetrf_single - not found
-- Found LAPACK library
-- Configuring done
-- Generating done

then when trying to compile an example i get many undefined references 
to `cblas_sgemm', `dgesvd_'

**Comment by bakercp** [comment]
Can you run 

https://github.com/bakercp/ofxDlib/blob/master/scripts/dependencies/linux64/install.sh

and then 

un-comment this  lines:

https://github.com/bakercp/ofxDlib/blob/master/addon_config.mk#L39

**Comment by bakercp** [comment]
This is fixed on the develop branch.  See the README for instructions on compiling dlib.
