### ISSUE TITLE
Use of undeclared identifier 'glm'

### ISSUE THREAD

**Issue by chriship** [bakercp/ofxDlib#9]
I'm getting issues from the use of glm. I found this: https://forum.openframeworks.cc/t/ofxcv-examples-problems/26199/4?u=csw

I'm using OF 0.9.8. Do I need to build OF from source to allow use of glm?

Thanks!

**Comment by bakercp** [comment]
See https://github.com/bakercp/ofxDlib/blob/master/README.md#compatibility.

Since we have no stable branch, the only option is using a nightly build our using OF from source.
